### ISSUE TITLE
Style DayPicker

### ISSUE THREAD

**Issue by gigawatson** [exploriter/roam-themes#2]
Today's date hard to distinguish on the dark scheme.

```css
.bp3-datepicker .DayPicker-Day.DayPicker-Day--isToday .bp3-datepicker-day-wrapper {
    border: 1px solid rgba(16,22,26,0.15);
}
```
